### ISSUE TITLE
Not so good json log format for Nginx in this guide

### ISSUE THREAD

**Issue by vincbe** [DataDog/the-monitor#110]
You are giving an example JSON log for Nginx in this guide : 
https://www.datadoghq.com/blog/how-to-monitor-nginx-with-datadog/#use-json-logs-for-automatic-parsing
it's quite a poor example as:
* it doesn't match with the standard attributes - http_user_agent should be in a http element to have the http.user_agent 
* and there's a collision with the reserved `status` attributes, that should be a `http.status_code` probably
* lot of interesting fields are still missing (X-forwarded-for ..

**Comment by davidmlentz** [comment]
Thanks! We've updated this post.
