### ISSUE TITLE
The "Metric to watch: Volume queue length" Section in The "Part 1: Key metrics for Amazon EBS monitoring" Article

### ISSUE THREAD

**Issue by shalano** [DataDog/the-monitor#117]
Hello All...

In the "[Metric to watch: Volume queue length](https://www.datadoghq.com/blog/amazon-ebs-monitoring/#disk-activity)" Section in The "[Part 1: Key metrics for Amazon EBS monitoring](https://www.datadoghq.com/blog/amazon-ebs-monitoring/)" article, it was mentioned that "A rule of thumb for SSD volumes is to aim for a queue length of one for every 500 IOPS available" and the source for that statement is https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/benchmark_procedures.html#UnderstandingQueueLength , which has been updated to be "we recommend that you target a queue length of 1 for every 1000 IOPS available".

So, Could you please update your article to reflect the latest changes in the documentation? 

Thank you,
Ahmed

**Comment by z0331** [comment]
Hi Ahmed,

Thanks for pointing this out. We've updated the article to reflect the new docs.
