### ISSUE TITLE
"Configure the Agent" section does not reflect NGINXPlus properly

### ISSUE THREAD

**Issue by WasiqulIslam** [DataDog/the-monitor#119]
In the section "Configure the Agent" there is a problem which delayed my integration.
This section is supposed to be for NGINX and not for NGINXPlus. For NGINXPlus we also have to add "use_plus_api: true" which is not mentioned in this guide.

**conf.yaml**

init_config:

instances:

  - nginx_status_url: http://localhost/nginx_status/
    tags:
      - instance:foo

**Comment by davidmlentz** [comment]
@WasiqulIslam Thank you for pointing this out. We've added a brief explanation and a link to documentation to address this.

**Comment by WasiqulIslam** [comment]
Welcome
