### ISSUE TITLE
documentation/blog post issue about haproxy metrics

### ISSUE THREAD

**Issue by speculatrix** [DataDog/the-monitor#128]
https://www.datadoghq.com/blog/how-to-collect-haproxy-metrics/

has this fragment
```
listen stats # Define a listen section called "stats"
  bind :9000 # Listen on localhost:9000
```

that does NOT make haproxy stats service bind only to localhost:9000

**Comment by davidmlentz** [comment]
Hi. Can you provide any further detail? We're using the default config in this case, and in our tests it does make stats available on :9000 and not, e.g., :9001.

Thanks.

**Comment by speculatrix** [comment]
Sorry, to clarify, the stats listener can be accessed from other hosts, not just the local machine.
I.e. It's not listening just on localhost, but binds to all ip addresses.
