### ISSUE TITLE
Submitting a new blog for Apache APISIX's Datadog Plugin

### ISSUE THREAD

**Issue by yzeng25** [DataDog/the-monitor#138]
Hello,

I am Yilin, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from GitHub: https://github.com/apache/apisix.

We recently released a plugin to integrate Datadog in Apache APISIX. I think the plugin is very meaningful for developers and both communities.In addition, it will help Datadog and Apache APISIX publicize and let more developers and companies know about us.

I am reaching out to you guys to see if we can have this blog posted here.What do you think?

**Comment by apigirl** [comment]
Hi @yzeng25 - we've added a separate PR [here](https://github.com/DataDog/documentation/pull/12345) to update this as per @jeremy-lqs email response to your original request.

**Comment by yzeng25** [comment]
> Hi @yzeng25 - we've added a separate PR [here](https://github.com/DataDog/documentation/pull/12345) to update this as per @jeremy-lqs email response to your original request.

Oh great! we will discuss in that PR then. Thanks!
