### ISSUE TITLE
How to enable nginx log collection by datadog for specific endpoints

### ISSUE THREAD

**Issue by devesh23** [DataDog/the-monitor#144]
I work on a product with multiple endpoints, but due to the sensitive nature of data, we are only looking to send Nginx logs for one endpoint. Does DataDog support it? If Yes, How can we enable it?

**Comment by davidmlentz** [comment]
Hi @devesh23 ! For help with that question, please [contact our support team](https://www.datadoghq.com/support/). Thanks!
