### ISSUE TITLE
DataDog Agent for PostgreSQL vs Tracing Postgres Queries with ddtrace 

### ISSUE THREAD

**Issue by saikdasari** [DataDog/the-monitor#147]
Hi,

We monitor our Postgres Database using the DataDog Agent for PostgreSQL as well as by tracing the queries our `Go` applications generate. We use the ddtrace's gorm package to trace the database queries.

When investigating the requests for a query, the values for `trace.postgres.query.hits` and `postgresql.queries.count` are returning completely different results within the same timeframe. 

Is this expected? Why is this happening?

**Comment by echang26** [comment]
Hi @saikdasari, I forwarded your question to a member of our Database Monitoring team and here's what they had to say:

> These metrics are collected with different methods meaning that the trace metric is collected through the tracer and the other one is through the Agent. The `trace.postgres.query.hits` metric shows how many times the application is hitting Postgres. The `postgresql.queries.count` metric shows the total query execution count per query_signature, db, and user. Since they are collected as different methods, there could be many factors for why their metrics don’t match exactly.

Hope this helps. If you have any further questions, please reach out to our support team: https://www.datadoghq.com/support/

**Comment by saikdasari** [comment]
I am interested to know what those factors are. 


My expectation when using the DataDog Postgres Agent is that it captures each and every execution of a query. Based on the data I am looking at, the tracer shows more hits for a query than the Agent.

Let me know if I rather create a support ticket for this.

**Comment by echang26** [comment]
@saikdasari Yes, I'd recommend creating a support ticket. Thanks!
