### ISSUE TITLE
example dashboard

### ISSUE THREAD

**Issue by drew-altana** [DataDog/the-monitor#153]
The article https://www.datadoghq.com/blog/monitor-elasticsearch-datadog/#building-custom-elasticsearch-dashboards
has a nice looking elasticsearch dashboard, can you provide the source? Even if it doesn't work out of the box I'd rather start with something.

**Comment by davidmlentz** [comment]
Hi! We don't have source code for that dashboard available, but it does have a lot of data in common with the current out of the box dashboard named "Elasticsearch - Overview," including available nodes, nodes by status, indexing latency, query and fetch latency. The OOTB overview dashboard also contains some log data, but not a log stream (shown in the right Logs column on the right of that screenshot). You can add this using a [list widget](https://docs.datadoghq.com/dashboards/widgets/list/).

If you [clone](https://docs.datadoghq.com/getting_started/dashboards/#start-by-reusing-other-dashboards) the "Elasticsearch - Overview" dashboard, you can add that log stream and any other adjustments to suit your needs.

Hope this helps. Thanks.

**Comment by drew-altana** [comment]
Don't know how I missed that one, thanks!
