### ISSUE TITLE
Time Maps

### ISSUE THREAD

**Issue by erik-stephens** [DataDog/the-monitor#17]
Apologies if this isn't the proper forum for this kind of feedback.   After reading the time series graph 101 blog post, I wanted to mention [this kind of visualization](https://districtdatalabs.silvrback.com/time-maps-visualizing-discrete-events-across-many-timescales) in case not on your roadmap already.  I haven't seen it available in any of the monitoring systems I've used.

**Comment by johnaxel** [comment]
Thanks @erik-stephens -- that's interesting. I'm happy to pass along a feature request to our developers. Do you have an example use case in mind where this visualization type would be especially useful?

**Comment by erik-stephens** [comment]
I think can apply generally to anyone looking for patterns but not sure where to look since you can see at various time scales (second, hour, day, etc).  Some ideas that come to mind:

- Help gauge priority of error events: high if fast & steady, lower if slow & steady, high if speeding up, lower if slowing down.

- Help detect potential abuse.

- Maybe tap into auto-scaling events to inform whether to reserve compute instances.

**Comment by johnaxel** [comment]
Thanks again, @erik-stephens. I've passed along your suggestion to our developers. Going to close this issue now, as it's being discussed and prioritized by our team. We appreciate the input!
