### ISSUE TITLE
HAproxy integration & SSL

### ISSUE THREAD

**Issue by neurogenesis** [DataDog/the-monitor#18]
If HAproxy isn't terminating SSL, the metrics look a bit misleading (large red number for 2xx).

Are there any plans to allow an alternate SSL passthrough centric dashboard? (connections per second, response times, etc.)

**Comment by vagelim** [comment]
@neurogenesis besides the metrics you listed above, are there any other metrics you'd like to see included on an SSL-passthrough centric dashboard (besides the metrics on the current default dashboard that apply to both use cases)

**Comment by vagelim** [comment]
At this point in time, we are unable to support multiple versions of a default screenboard. If you would like some help creating one for yourself, please reach out and let me know.
