### ISSUE TITLE
Monitor Backends UP / DOWN

### ISSUE THREAD

**Issue by Steve-Fenton** [DataDog/the-monitor#25]
Hello,

I have a HAProxy questionn.

Is it possible to monitor the number of backends currently UP / DOWN (the kind of thing you can see by opening HATOP)?

I'd quite like to see that information and have monitors against it.

Thanks for your help.

**Comment by vagelim** [comment]
@Steve-Fenton you most certainly can. The metric you want to create a monitor for is `haproxy.count_per_status`. To specify the status, use a key:value pair, with `status` as the key (ex: `status:up`).

See the screenshot below for more detail:

[![HAProxy metric monitor count per status](https://i.imgur.com/4L7TQN2.png)](https://i.imgur.com/4L7TQN2.png)

**Comment by vagelim** [comment]
Does that help @Steve-Fenton ?

**Comment by Steve-Fenton** [comment]
@vagelim thanks for getting back to me - I have lots of HAProxy metrics listed, but not this one...

![haproxy](https://cloud.githubusercontent.com/assets/1036595/15674247/a39bfd76-2733-11e6-900f-a14a05b8de23.png)

I have the HAProxy integration listed, and I can see lots of `haproxy.backend...` and `haproxy.frontend...` stats.

Do I need to configure the collector to get more information?

**Comment by vagelim** [comment]
@Steve-Fenton 

Sorry! 
I forgot that you need to enable the `collect_status_metrics` and `collect_status_metrics_by_host` parameters in your `haproxy.yaml` file ([see this line](https://github.com/DataDog/dd-agent/blob/master/conf.d/haproxy.yaml.example#L21-26)). 

Let me know if that works for you.

**Comment by Steve-Fenton** [comment]
Perfect - all working as described.

Thank you for your help.

**Comment by vagelim** [comment]
I'm glad I could help!
