### ISSUE TITLE
Pseudo file location on CoreOS

### ISSUE THREAD

**Issue by ssro** [DataDog/the-monitor#30]
Hi folks,

Yesterday I ran into an issue about collecting docker metrics on CoreOS v. 1068.6.0 using a shell script. I was trying to collect memory usage of a container by cat-ing the following file `/sys/fs/cgroup/memory/system.slice/docker-$CONTAINER_ID/memory.usage_in_bytes`
All the time I was getting the same value and it wasn't the right one. Digging around I've found that this file has been moved at `/sys/fs/cgroup/memory/init.scope/system.slice/docker-$CONTAINER_ID/memory.usage_in_bytes`

So basically the path for the metrics in newer versions of CoreOS has been changed from `/sys/fs/cgroup/<METRIC>/system.slice/docker-$CONTAINER_ID/<METRIC_VALUE>` to `/sys/fs/cgroup/<METRIC>/init.scope/system.slice/docker-$CONTAINER_ID/<METRIC_VALUE>`

The testing has been done against 2 CoreOS clusters. One cluster has version 1010.6.0 and the other one 1068.6.0. Also the new path exists in the latest version of CoreOS (1068.9.0).

Maybe you should update the [metrics collection](https://github.com/DataDog/the-monitor/blob/master/docker/3_how_to_collect_docker_metrics.md) page

Thanks!

**Comment by johnaxel** [comment]
Thanks for the detailed report @ssro! We'll update the article shortly.

**Comment by johnaxel** [comment]
Thanks again for this report @ssro. The new information has now been pushed to github and updated on our blog post: https://www.datadoghq.com/blog/how-to-collect-docker-metrics/

**Comment by ssro** [comment]
Hello everyone! Not sure if I should open a new issue, but I just want to mention that the latest CoreOS version, has changed (again) the metrics location. If last time the location was `/sys/fs/cgroup/<METRIC>/init.scope/system.slice/docker-$CONTAINER_ID/<METRIC_VALUE>` (CoreOS 1068.9.0) now it has been moved to `/sys/fs/cgroup/<METRIC>/docker/<CONTAINER_ID>/<METRIC_VALUE>`

CoreOS stable (1185.3.0)
Docker version 1.11.2

Will keep updating this for newer releases of CoreOS, in case the location of metrics change (again)

Thanks!

**Comment by johnaxel** [comment]
Thanks @ssro — I'll update these paths shortly.

**Comment by johnaxel** [comment]
Thank you again @ssro!
