### ISSUE TITLE
HAProxy config not correct for latest version on blog post

### ISSUE THREAD

**Issue by cdancette** [DataDog/the-monitor#34]
On the page https://www.datadoghq.com/blog/how-to-collect-haproxy-metrics/, the parameters to enable stats on HAProxy doesn't work with the latest version (1.6) : https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4

`listen stats :9000` should be replaced by
```
listen stats
bind :9000
```

**Comment by cdancette** [comment]
PR #35

**Comment by vagelim** [comment]
Resolved w/merge of https://github.com/DataDog/the-monitor/pull/35
