### ISSUE TITLE
Stats API won't return anything

### ISSUE THREAD

**Issue by Aamir010** [DataDog/the-monitor#4]
<img width="600" alt="screen shot 2016-01-04 at 12 41 04 pm" src="https://cloud.githubusercontent.com/assets/13231166/12087450/fb061f4c-b2f8-11e5-8d43-2978ea0b1a9d.png">

**Comment by johnaxel** [comment]
Thanks for flagging this, @Aamir010—do you know what might be the cause, @kky?

**Comment by Aamir010** [comment]
-q -1 will solve the problem.

echo -ne "GET /containers/d2364abec1d4/stats HTTP/1.1\r\n\r\n" | nc -q -1 -U /var/run/docker.sock
