### ISSUE TITLE
Way to collect network statistics not complete

### ISSUE THREAD

**Issue by acshekhara1** [DataDog/the-monitor#41]
Hi,
  suggested method to look at network stats works only if there is only one process inside a container. In most of the cases, we might have a shell script launching all the other required processes and entering into an infinite loop or monitoring applications that were launched.

**Comment by vagelim** [comment]
Hi @acshekhara1, which post is this in reference to?

**Comment by acshekhara1** [comment]
Hi
 I was talking about this. This will not be giving correct stats. In my opinion, it has to collect stats of all the processes inside the container and sum them up.



https://www.datadoghq.com/blog/how-to-collect-docker-metrics/ <https://www.datadoghq.com/blog/how-to-collect-docker-metrics/>
NetworkDocker version 1.6.1 and greaterIn release 1.6.1 <https://github.com/docker/docker/blob/master/CHANGELOG.md#161-2015-05-07>, Docker fixed read/write /proc paths.
$ CONTAINER_PID=`docker inspect -f '{{ .State.Pid }}' $CONTAINER_ID`
$ cat /proc/$CONTAINER_PID/net/dev    
    
With regards,
Chandrashekhara A

**Comment by vagelim** [comment]
Hi @acshekhara1, I have run these commands myself which yields the output below:

```
 => cat /proc/11987/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:    5796      45    0    0    0     0          0         0      648       8    0    0    0     0       0          0
```

This indicates that the network metrics reported are by interface, not per-process. In this case, the PID refers to the _container_, not any single process from within the container. So ultimately, that means the metrics reported are an aggregate of all running processes in the container, which seems to be exactly what you want when you said:

> it has to collect stats of all the processes inside the container and sum them up.

As the current blog reflects the method to retrieve aggregate network metrics from the container, I will close this issue. Thank you!
