### ISSUE TITLE
Broken link to Oracle's GC01 tutorial in ES article

### ISSUE THREAD

**Issue by consulthys** [DataDog/the-monitor#45]
In the [Garbage Collection section](https://github.com/DataDog/the-monitor/blob/master/elasticsearch/how_to_monitor-elasticsearch_performance.md#garbage-collection) of the "How to monitor Elasticsearch performance" article, the link to Oracle's Garbage Collection article is not working anymore:
http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html

Keep up the great work, those articles rock!

**Comment by echang26** [comment]
I updated the link [here](https://github.com/DataDog/the-monitor/pull/46) @consulthys 

Thanks for bringing this to our attention!
