### ISSUE TITLE
Kubernetes custom application metrics.

### ISSUE THREAD

**Issue by sa-mao** [DataDog/the-monitor#53]
Hello, I'm wondering if the dd-agent can collect custom applications metrics exposed to cadvisor, without the need to use statsd agent.

**Comment by johnaxel** [comment]
@hkaj Can you advise?

**Comment by hkaj** [comment]
That's not supported yet. Our only use of cadvisor is for container system metrics through the `/api/v1.3/subcontainers/` endpoint.

**Comment by johnaxel** [comment]
Thanks for the clarification @hkaj !

@sa-mao, I'll close this issue for now. Let us know if we can be of further help.
