### ISSUE TITLE
Template Elasticsearch Timeboard indexing/query latency might be wrong

### ISSUE THREAD

**Issue by yaoxiaotong** [DataDog/the-monitor#55]
The template chart of indexing latency and query latency might be wrong. It shows different with Kibana. 

Take query latency for example. The template is using rate of fetch time and rate of query time like this: 
![image](https://user-images.githubusercontent.com/11626122/26841611-e61842ec-4a9e-11e7-9d7d-dd38dadf40aa.png)

It might be better to use derivatives to get the same chart with Kibana like this: 
(derivative of fetch time + derivative of query time ) / derivative of query total 

![image](https://user-images.githubusercontent.com/11626122/26841667-23bded72-4a9f-11e7-998e-f4a29150a34f.png)

The json of this is 

`{
  "viz": "timeseries",
  "status": "done",
  "requests": [
    {
      "q": "( derivative(sum:elasticsearch.search.fetch.time{$cluster}) + derivative(sum:elasticsearch.search.query.time{$cluster}) ) * 1000 / derivative(sum:elasticsearch.search.query.total{$cluster})",
      "aggregator": "avg",
      "conditional_formats": [],
      "type": "line"
    }
  ],
  "autoscale": true
}`

**Comment by johnaxel** [comment]
Thanks for the report @yaoxiaotong. Can you take a look @echang26 ?

**Comment by echang26** [comment]
Hi @yaoxiaotong thanks for bringing this to our attention. We used your suggestion to apply a fix to our default Elasticsearch timeboard's indexing and query latency graphs, and it does look like those graphs are now more similar to the ones shown in Marvel/Kibana (see below). 

![screen shot 2017-06-27 at 4 06 18 pm](https://user-images.githubusercontent.com/6857425/27607808-2bf9131c-5b53-11e7-9358-c5787f9849c0.png)

Thanks for letting us know.

**Comment by yaoxiaotong** [comment]
@johnaxel  @echang26  thanks for your response and fixing. This solved the problem.

**Comment by johnaxel** [comment]
Thanks for the report!
