### ISSUE TITLE
Current monitoring for openstack with neutron instead of Nova

### ISSUE THREAD

**Issue by craigpero** [DataDog/the-monitor#59]
Does DataDog monitor openstack now that Neutron is the preferred component?  The document written in 2015 goes into detail over monitoring with Nova but that is not an option for those using Neutron.

https://www.datadoghq.com/blog/openstack-monitoring-nova/

**Comment by vagelim** [comment]
Hi @craigpero,
Neutron is the networking component of OpenStack, and does not replace Nova, the compute component. Could you explain what you mean by, "but that is not an option for those using Neutron."? Again, Nova and Neutron serve distinct purposes and you don't use one to the exclusion of the other.

**Comment by johnaxel** [comment]
Closing this for now, but please let us know if you have more info to share here @craigpero
