### ISSUE TITLE
Issue with jqmath on the-monitor/redis/how_to_monitor_redis_performance.md

### ISSUE THREAD

**Issue by SamCyanide** [DataDog/the-monitor#60]
Under some sections, the jqmath rendered text has subscript letters where it should not.

**Metric to watch: hit rate**
![hit rate jqmath](http://i.imgur.com/LksIjOB.png)

**Metric to alert on: mem_fragmentation_ratio**
![mem fragmentation jqmath](http://i.imgur.com/FmzltCW.png)

**Comment by johnaxel** [comment]
Thanks for the report @SamCyanide — looks like something got lost in translation here. We'll get it fixed
