### ISSUE TITLE
Spark api's

### ISSUE THREAD

**Issue by BhandariArpan** [DataDog/the-monitor#74]
Is there any road map to add documentation apis for spark as well ?

**Comment by johnaxel** [comment]
Hi @BhandariArpan — could you elaborate a bit more? Are you asking if/when we plan to write about the monitoring APIs for Spark?

**Comment by BhandariArpan** [comment]
Hi @johnaxel : Yes the same as you have provided for Hadoop.

**Comment by johnaxel** [comment]
Gotcha @BhandariArpan — thanks for the clarification. It's not in the immediate plans for 2018 but we would like to produce a guide for Spark at some point. Will take your request into account as we plan for the future!
